### ISSUE TITLE
JUnit report is attached to wrong job when more than one job is executed

### ISSUE THREAD

**Issue by AleksanderBrzozowski** [allegro-actions/junit-reporter#88]
We have a service which contains two workflows:
- Build & Publish - for building & publishing **(here we use junit reporter)**
- issue - for checking JIRA issue presence in commit messages

**Steps to reproduce:**
When both workflows were executed, junit report was wrongly attached to `issue` workflow instead of `Build & Publish` workflow.
![image](https://user-images.githubusercontent.com/15987499/128699470-eb37b6f6-2802-485c-bac6-1e8c18d046c6.png)

**Expected behaviour**
Junit report should be attached to workflow from which it was executed.

**Similar issues**
https://github.com/mikepenz/action-junit-report/issues/40
https://github.community/t/github-actions-status-checks-created-on-incorrect-check-suite-id/16685
https://github.com/EnricoMi/publish-unit-test-result-action/issues/12

**Possible solutions**
JUnit reporter github action should update existing check instead of creating new one.
There should be an option to set this behaviour, for example:
```yaml
- uses: allegro-actions/junit-reporter@v1
  with:
    update-existing-check: true # or other name?
    path: 'test-results/**/TEST-*.xml'
```
Get check which triggered action:
https://docs.github.com/en/rest/reference/checks#get-a-check-run

Update this check with provided information about test results:
https://docs.github.com/en/rest/reference/checks#update-a-check-run

When using the action like this, we would write such workflow:
```yaml
jobs:
  build:
    steps:
      - ... run tests

       # we can zip the results and then unzip them when downloading
      - name: Upload test results as artifact
        uses: actions/upload-artifact@v2
        if: ${{ success() || failure() }}
        with:
          name: test-results
          path: '**/build/test-results/**/TEST-*.xml'

  report-test-results:
    needs: build
    if: ${{ success() || failure() }}

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: test-results
          path: test-results
      - uses: allegro-actions/junit-reporter@v1
        with:
          path: 'test-results/**/TEST-*.xml'

```
